---
- name: Ensure lego is present
  ansible.builtin.package:
    name: golang-github-acme-lego
    state: present
- name: Ensure the binary is properly located
  ansible.builtin.copy:
    src: gtfsproxy
    dest: /usr/local/bin/gtfsproxy
    owner: root
    group: root
    mode: 0755
- name: Ensure the Systemd units file are deployed
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - gtfsproxy.service
    - gtfsdownload.service
    - gtfsdownload.timer
  register: systemd_daemons
- name: Reload systemd daemons if needed
  ansible.builtin.systemd:
    daemon_reload: true
- name: Ensure the service is started and enabled
  ansible.builtin.service:
    name: gtfsproxy.service
    state: started
    enabled: true
- name: Ensure the downloader timer is started and enabled
  ansible.builtin.service:
    name: gtfsdownload.timer
    state: started
    enabled: true
