---
- name: Ensure git is present
  ansible.builtin.package:
    name: git
    state: present
- name: Ensure user gtfs is present
  ansible.builtin.user:
    name: gtfs
    state: present
- name: Checkout the transitland-atlas
  ansible.builtin.git:
    repo: 'https://github.com/fale/transitland-atlas.git'
    dest: /home/gtfs/transitland-atlas
    version: gtfsproxy
    clone: true
    update: true
  become: true
  become_user: gtfs
- name: Ensure the binary is properly located
  ansible.builtin.copy:
    src: gtfsproxy
    dest: /usr/local/bin/gtfsproxy
    owner: root
    group: root
    mode: 0755
- name: Ensure the Systemd units file are deployed
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - gtfsproxy.service
    - gtfsdownload.service
    - gtfsdownload.timer
    - gtfsimport.service
    - gtfsimport.timer
  register: systemd_daemons
- name: Reload systemd daemons if needed
  ansible.builtin.systemd:
    daemon_reload: true
- name: Ensure the service is started and enabled
  ansible.builtin.service:
    name: gtfsproxy.service
    state: started
    enabled: true
- name: Ensure the timers are started and enabled
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - gtfsdownload.timer
    - gtfsimport.timer
